name: Deploy Lambda

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: |
          npm install

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Package Lambda function
        run: |
          zip -r function.zip index.js node_modules/ # Inclui index.js e node_modules

      - name: Check if Lambda function exists
        id: check-lambda
        run: |
          FUNCTION_EXISTS=$(aws lambda get-function --function-name techchallenge-authorizer-lambda --query 'Configuration.FunctionName' --output text 2>/dev/null || echo "")
          echo "FUNCTION_EXISTS=${FUNCTION_EXISTS}" >> $GITHUB_ENV

      - name: Debug FUNCTION_EXISTS
        run: |
          echo "Function Exists: $FUNCTION_EXISTS"

      - name: Deploy Lambda function
        run: |
          if [ "${{ env.FUNCTION_EXISTS }}" = "techchallenge-authorizer-lambda" ]; then
            echo "Updating existing Lambda function..."
            aws lambda update-function-code --function-name techchallenge-authorizer-lambda --zip-file fileb://function.zip
            aws lambda update-function-configuration --function-name techchallenge-authorizer-lambda --environment "USER_POOL_ID=us-east-1_EXlHzpLBS,CLIENT_ID=6d1oc64ts7urk81mcaltc3ip68"
          else
            echo "Creating new Lambda function..."
            aws lambda create-function --function-name techchallenge-authorizer-lambda \
              --zip-file fileb://function.zip \
              --handler index.handler \
              --runtime nodejs12.x \
              --role arn:aws:iam::417263883456:role/LabRole \
              --environment "USER_POOL_ID=us-east-1_EXlHzpLBS,CLIENT_ID=6d1oc64ts7urk81mcaltc3ip68"
          fi
